[config]
set_wallpaper = true
wallpaper_tool = "Swww"
prefix = "@"
swww_options = [
	"--transition-type",
	"center"
]
reload_apps = true

[config.reload_apps_list]
waybar = true
kitty = true
gtk_theme = true

[templates.hyprland]
input_path = "/home/p4rad0x/.config/matugen/templates/hypr.matugen.template"
output_path = "/home/p4rad0x/.config/hypr/hypr-colours.conf"

[templates.gtk3]
input_path = "/home/p4rad0x/.config/matugen/templates/gtk.matugen.template"
output_path = "/home/p4rad0x/.config/gtk-3.0/colours.css"

[templates.gtk4]
input_path = "/home/p4rad0x/.config/matugen/templates/gtk.matugen.template"
output_path = "/home/p4rad0x/.config/gtk-4.0/colours.css"

[templates.waybar]
input_path = "/home/p4rad0x/.config/matugen/templates/css.matugen.template"
output_path = "/home/p4rad0x/.config/waybar/colours.css"

[templates.rofi]
input_path = "/home/p4rad0x/.config/matugen/templates/rofi.matugen.template"
output_path = "/home/p4rad0x/.config/rofi/colours.rasi"